### ISSUE TITLE
Improve description of how to define and use custom elements

### ISSUE THREAD

**Issue by speth** [Cantera/cantera-website#243]
The description of how to use custom elements within a phase definition is a bit confusing (see a recent [Users' Group](https://groups.google.com/g/cantera-users/c/OAuoyNtm0KY) post). I think this is mainly due to two things:
1. the lack of a complete example that includes both the top-level elements *section* where the new elements are defined as well as the elements *field* within the phase definition.
2. The fact that on the page describing phase definitions (https://cantera.org/tutorials/yaml/phases.html), the examples show partial phase definitions without the outer structure, making them look like top-level sections, e.g. 
```yaml
elements:
- default: [C, H, Ar]
- isotopes: [O18]
- myelements.yaml/uranium: [U235, U238]
```
